#include <Arduino.h>
#include <BLEDevice.h>

#define DEVICE_INFORMATION_SERVICE_UUID BLEUUID((uint16_t) 0x180a)
#define MANUFACTURE_NAME_CHARACTERISTIC_UUID BLEUUID((uint16_t) 0x2a29)
#define SERIAL_NUMBER_STRING_CHARACTERISTIC_UUID BLEUUID((uint16_t) 0x2a25)

BLEServer * SERVER;
BLEService * DEVICE_INFORMATION_SERVICE;
BLECharacteristic * MANUFACTURE_NAME_CHARACTERISTIC;
BLECharacteristic * SERIAL_NUMBER_STRING_CHARACTERISTIC;

void setup() {
  BLEDevice::init("ESP32_TEST");
  SERVER = BLEDevice::createServer();

  DEVICE_INFORMATION_SERVICE = SERVER->createService(DEVICE_INFORMATION_SERVICE_UUID);

  MANUFACTURE_NAME_CHARACTERISTIC = DEVICE_INFORMATION_SERVICE->createCharacteristic(
    MANUFACTURE_NAME_CHARACTERISTIC_UUID,
    BLECharacteristic::PROPERTY_READ
  );
  MANUFACTURE_NAME_CHARACTERISTIC->setValue("Takram");

  SERIAL_NUMBER_STRING_CHARACTERISTIC = DEVICE_INFORMATION_SERVICE->createCharacteristic(
    SERIAL_NUMBER_STRING_CHARACTERISTIC_UUID,
    BLECharacteristic::PROPERTY_READ
  );
  SERIAL_NUMBER_STRING_CHARACTERISTIC->setValue("Serial 0A");

  DEVICE_INFORMATION_SERVICE->start();
  SERVER->startAdvertising();
}

void loop() {
}
